# Generated by Django 5.1.4 on 2024-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=2)),
                ('week_parity', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_type', models.CharField(choices=[('Л', 'Лекция'), ('ПР', 'Практическое занятие'), ('ЛР', 'Лабораторное занятие'), ('КП', 'Курсовой проект'), ('КР', 'Курсовая работа')], max_length=2)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
