# Generated by Django 4.2.16 on 2024-12-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=2)),
                ('week_parity', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=511)),
                ('start_time', models.TimeField()),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
