# Generated by Django 5.1.4 on 2024-12-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_options_remove_task_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='week_parity',
        ),
    ]
