# Generated by Django 5.1.4 on 2024-12-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
    ]
