# Generated by Django 5.1.4 on 2024-12-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_task_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week_parity',
            field=models.CharField(choices=[('Ч', 'Чётная'), ('Н', 'Нечётная'), ('Б', 'Обе')], default='Ч', max_length=2),
        ),
    ]
