# Generated by Django 5.1.4 on 2024-12-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_lesson_week_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_parse',
            field=models.BooleanField(default=False),
        ),
    ]
