# Generated by Django 5.1.1 on 2024-11-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
